## default connection pool
server:
  port: 8080
debug: true
spring:
  config:
    import: env.properties
  sql:
    init:
      platform: mongodb
      mode: always
  output:
    ansi:
      enabled: always
#  datasource:
#    url: jdbc:postgresql://localhost:5432/${PSQL_DB}
#    username: ${PSQL_USER}
#    password: ${PSQL_PASSWORD}
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    defer-datasource-initialization: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DATABASE}
      database: ${MONGO_DATABASE}

jwt:
  secret: ${JWT_256_BIT_SECRET}

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR