## default connection pool
server:
  port: 8080
debug: true
spring:
#  sql:
#    init:
#      platform: mongodb
#      mode: always
#  config:
#   import: env.properties
  sql:
    init:
      platform: postgresql
      mode: always
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/org_info #${PSQL_DB}
    username: postgres #${PSQL_USER}
    password: postgres #${PSQL_PASSWORD}
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # none, create ...
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DATABASE}
      database: ${MONGO_DATABASE}
jwt:
  secret: ${JWT_256_BIT_SECRET}

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
