services:
  mongo:
    image: mongo
    container_name: autosurvey
    hostname: mongo
    restart: unless-stopped
  Environment:
  MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
  MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  MONGO_DB_USERNAME: ${MONGO_USER}
  MONGO_DB_PASSWORD: ${MONGO_PASSWORD}
